In [1]:
import numpy as np

In [2]:
datalines = open(r"C:\Users\nothi\Google Drive\Studies\Courses\Thesis\datasets\Temporal graphs\RealityMining\RealityMining.csv", 'r').readlines()
outliers = open(r"C:\Users\nothi\Google Drive\Studies\Courses\Thesis\datasets\Temporal graphs\RealityMining\Reality_Mining_gt.csv", 'r').readlines()
print(datalines[:10])
datalines = [row.replace('\n', '').split(',') for row in datalines]
print(datalines[:10])
datalines = datalines[1:]

['time,src,dst\n', '38259,97,9444\n', '38259,97,9444\n', '38362,60,6156\n', '38362,60,6156\n', '38365,60,6156\n', '38200,107,5\n', '38200,107,5\n', '38200,107,5\n', '38200,107,5\n']
[['time', 'src', 'dst'], ['38259', '97', '9444'], ['38259', '97', '9444'], ['38362', '60', '6156'], ['38362', '60', '6156'], ['38365', '60', '6156'], ['38200', '107', '5'], ['38200', '107', '5'], ['38200', '107', '5'], ['38200', '107', '5']]


In [3]:
datalines[:10]

[['38259', '97', '9444'],
 ['38259', '97', '9444'],
 ['38362', '60', '6156'],
 ['38362', '60', '6156'],
 ['38365', '60', '6156'],
 ['38200', '107', '5'],
 ['38200', '107', '5'],
 ['38200', '107', '5'],
 ['38200', '107', '5'],
 ['38200', '107', '5']]

In [4]:
times, froms, tos = zip(*[d for d in datalines if d[0] not in outliers])

In [5]:
int_froms = list(map(int, froms))
int_tos = list(map(int, tos))
int_times = list(map(lambda x: 60*60*24*int(x), times))

In [6]:
HOUR_IN_SECONDS = 60*60
FOUR_HOURS_IN_SECONDS = HOUR_IN_SECONDS * 4
DAY_IN_SECONDS = HOUR_IN_SECONDS*24
WEEK_IN_SECONDS = DAY_IN_SECONDS*7
MONTH_IN_SECONDS = DAY_IN_SECONDS*30
YEAR_IN_SECONDS = DAY_IN_SECONDS*365

In [7]:
min_time = np.min(int_times)
max_time = np.max(int_times)
time_span_seconds = max_time-min_time
num_of_hours = int(np.ceil(time_span_seconds/HOUR_IN_SECONDS))
num_of_four_hours = int(np.ceil(time_span_seconds/FOUR_HOURS_IN_SECONDS))
num_of_days = int(np.ceil(time_span_seconds/DAY_IN_SECONDS))
num_of_weeks = int(np.ceil(time_span_seconds/WEEK_IN_SECONDS))
num_of_months = int(np.ceil(time_span_seconds/MONTH_IN_SECONDS))
num_of_years = int(np.ceil(time_span_seconds/YEAR_IN_SECONDS))


In [8]:
max_time - 3330547200

0

In [9]:
print(f"num of hours: {num_of_hours}, num of four hours: {num_of_four_hours}, num of days: {num_of_days}, num of weeks: {num_of_weeks}, num of months: {num_of_months}, num of years: {num_of_years}".format())

num of hours: 8352, num of four hours: 2088, num of days: 348, num of weeks: 50, num of months: 12, num of years: 1


In [10]:
np.histogram(int_times, bins=num_of_hours)

(array([179,   0,   0, ...,   0,   0,   8], dtype=int64),
 array([3.3004800e+09, 3.3004836e+09, 3.3004872e+09, ..., 3.3305400e+09,
        3.3305436e+09, 3.3305472e+09]))

In [11]:
np.histogram(int_times, bins=num_of_four_hours)

(array([179,   0,   0, ...,   0,   0,   8], dtype=int64),
 array([3.3004800e+09, 3.3004944e+09, 3.3005088e+09, ..., 3.3305184e+09,
        3.3305328e+09, 3.3305472e+09]))

In [12]:
np.histogram(int_times, bins=num_of_days)

(array([ 179,  196,  176,  140,  143,  124,  430,  209,  936,  979,  796,
         777,  957,  458,  559,  984, 1112,  576, 1303,  579, 1051, 1140,
        1351, 1011,  659, 1358, 1531,  690,  998, 1486, 1572, 1462, 1989,
        1788,  691,  552,  454, 2131, 2436, 3118, 4000, 2654, 2483, 3026,
        3291, 3133, 3165, 3917, 1938, 2294, 3171, 2512, 3231, 3857, 4082,
        2486, 2383, 4307, 3963, 3931, 3858, 3643, 2520, 1924, 4042, 3645,
        4223, 4704, 3764, 2997, 2389, 2656, 4470, 4632, 4963, 5697, 4017,
        3865, 5342, 5342, 4640, 5594, 4710, 3214, 3321, 5264, 4977, 4944,
        5938, 4792, 3585, 3971, 5260, 5716, 5542, 5300, 4801, 3350, 3039,
        4858, 4799, 4661, 3674, 4429, 3143, 2869, 5379, 5795, 5861, 5751,
        5265, 3684, 3181, 6044, 6021, 4524, 2179, 2470, 2631, 2328, 5266,
        6300, 6311, 5528, 5084, 3828, 3346, 4862, 4342, 4722, 4310, 4503,
        3451, 3128, 4531, 4464, 4700, 3870, 3539, 2063, 1683, 2986, 2508,
        2609, 2107, 1584, 1066, 1173, 

In [13]:
np.histogram(int_times, bins=num_of_weeks)

(array([ 1388,  5112,  6164,  7740,  9986, 15345, 20953, 21633, 24605,
        25299, 28824, 32707, 32821, 33940, 28603, 34604, 27050, 34645,
        29536, 26295, 14543,  9417, 15876, 19074, 16202, 18162, 14710,
        14699, 13338, 13932, 17011, 15073, 14811, 10664, 13116,  9880,
        10061,  8921,  8915,  6624,  3203,  2799,  2598,  1844,  2177,
         1438,  1083,   370,   317,   297], dtype=int64),
 array([3.30048000e+09, 3.30108134e+09, 3.30168269e+09, 3.30228403e+09,
        3.30288538e+09, 3.30348672e+09, 3.30408806e+09, 3.30468941e+09,
        3.30529075e+09, 3.30589210e+09, 3.30649344e+09, 3.30709478e+09,
        3.30769613e+09, 3.30829747e+09, 3.30889882e+09, 3.30950016e+09,
        3.31010150e+09, 3.31070285e+09, 3.31130419e+09, 3.31190554e+09,
        3.31250688e+09, 3.31310822e+09, 3.31370957e+09, 3.31431091e+09,
        3.31491226e+09, 3.31551360e+09, 3.31611494e+09, 3.31671629e+09,
        3.31731763e+09, 3.31791898e+09, 3.31852032e+09, 3.31912166e+09,
        3.3

In [14]:
def split_by_time_scale(min_time, max_time, time_range, time_scale):
    times = []
    for i in range(time_range):
        time_start = min_time + i*(time_scale)
        time_end = np.min([max_time, min_time + (i+1)*(time_scale)])
        times.append((time_start, time_end))
    return times

In [15]:
hours = split_by_time_scale(min_time, max_time, num_of_hours, HOUR_IN_SECONDS)

In [16]:
four_hours = split_by_time_scale(min_time, max_time, num_of_four_hours, FOUR_HOURS_IN_SECONDS)

In [17]:
days = split_by_time_scale(min_time, max_time, num_of_days, DAY_IN_SECONDS)

In [18]:
weeks = split_by_time_scale(min_time, max_time, num_of_weeks, WEEK_IN_SECONDS)

In [19]:
months = split_by_time_scale(min_time, max_time, num_of_months, MONTH_IN_SECONDS)

In [20]:
years = split_by_time_scale(min_time, max_time, num_of_years, YEAR_IN_SECONDS)

In [21]:
print(f"num of hours: {len(hours)}, num of four hours: {len(four_hours)}, num of days: {len(days)}, num of weeks: {len(weeks)}, num of months: {len(months)}, num of years: {len(years)}".format())

num of hours: 8352, num of four hours: 2088, num of days: 348, num of weeks: 50, num of months: 12, num of years: 1


In [22]:
def split_graphs_by_scale(min_time, time_range, time_scale):
    graphs_split = [[] for i in range(time_range)]
    for n1, n2, t in zip(int_froms, int_tos, int_times):
        time_egde_belongs_to = int(np.floor((t - min_time) / time_scale))
        if time_egde_belongs_to == len(graphs_split):
            time_egde_belongs_to -= 1
        if (n1 == n2):
            continue
        graphs_split[time_egde_belongs_to].append((n1, n2))
    return graphs_split

3600

In [23]:
graphs_split_to_hours = split_graphs_by_scale(min_time, num_of_hours, HOUR_IN_SECONDS)

In [24]:
graphs_split_to_four_hours = split_graphs_by_scale(min_time, num_of_four_hours, FOUR_HOURS_IN_SECONDS)

In [25]:
graphs_split_to_days = split_graphs_by_scale(min_time, num_of_days, DAY_IN_SECONDS)

In [26]:
graphs_split_to_weeks = split_graphs_by_scale(min_time, num_of_weeks, WEEK_IN_SECONDS)

In [27]:
graphs_split_to_months = split_graphs_by_scale(min_time, num_of_months, MONTH_IN_SECONDS)

In [28]:
graphs_split_to_years = split_graphs_by_scale(min_time, num_of_years, YEAR_IN_SECONDS)

In [29]:
# print('hour graphs num of edges:')
# for g in graphs_split_to_hours:
#     print(len(g))

# print('four hour graphs num of edges:')
# for g in graphs_split_to_four_hours:
#     print(len(g))

print('day graphs num of edges:')
for g in graphs_split_to_days:
    print(len(g))

print('week graphs num of edges:')
for g in graphs_split_to_weeks:
    print(len(g))

print('month graphs num of edges:')
for g in graphs_split_to_months:
    print(len(g))
    
print('year graphs num of edges:')
for g in graphs_split_to_years:
    print(len(g))

day graphs num of edges:
165
192
172
138
142
123
427
208
879
885
765
734
905
440
527
964
1099
575
1144
576
1005
1127
1328
987
650
1305
1502
690
997
1479
1551
1462
1928
1717
685
550
451
2098
2355
3095
3953
2625
2458
2996
3260
3102
3130
3875
1930
2261
3092
2495
3187
3800
4036
2481
2367
4275
3943
3900
3837
3614
2509
1914
4003
3622
4189
4653
3727
2968
2364
2641
4424
4566
4927
5674
3968
3801
5274
5312
4608
5544
4656
3191
3300
5226
4917
4880
5886
4737
3554
3946
5224
5680
5487
5262
4761
3334
3029
4826
4753
4639
3624
4387
3104
2839
5337
5759
5811
5693
5202
3661
3143
5978
5970
4488
2163
2459
2601
2291
5215
6251
6243
5487
5022
3792
3323
4819
4287
4668
4268
4460
3418
3100
4473
4423
4649
3849
3485
2038
1664
2944
2498
2585
2096
1578
1055
1160
1326
1318
1371
1331
1316
1483
1099
2327
2441
3158
2536
2867
1287
1584
3075
3006
3016
2856
3242
2062
1567
2329
2851
2968
3070
3278
1880
1423
2224
2869
3031
3221
3244
1306
1151
2320
2349
2537
2433
2450
1479
1225
2100
2940
2496
2374
1903
1014
973
2218
2619
2001
2

In [30]:
import networkx as nx

In [31]:
nx_graphs_split_to_hours = list(map(nx.Graph, graphs_split_to_hours))
nx_graphs_split_to_four_hours = list(map(nx.Graph, graphs_split_to_four_hours))
nx_graphs_split_to_days = list(map(nx.Graph, graphs_split_to_days))
nx_graphs_split_to_weeks = list(map(nx.Graph, graphs_split_to_weeks))
nx_graphs_split_to_months = list(map(nx.Graph, graphs_split_to_months))
nx_graphs_split_to_years = list(map(nx.Graph, graphs_split_to_years))

In [32]:
num_of_nodes_per_hour = [g.number_of_nodes() for g in nx_graphs_split_to_hours]
num_of_nodes_per_four_hours = [g.number_of_nodes() for g in nx_graphs_split_to_four_hours]
num_of_nodes_per_day = [g.number_of_nodes() for g in nx_graphs_split_to_days]
num_of_nodes_per_week = [g.number_of_nodes() for g in nx_graphs_split_to_weeks]
num_of_nodes_per_month = [g.number_of_nodes() for g in nx_graphs_split_to_months]
num_of_nodes_per_year = [g.number_of_nodes() for g in nx_graphs_split_to_years]

num_of_edges_per_hour = [g.number_of_edges() for g in nx_graphs_split_to_hours]
num_of_edges_per_four_hours = [g.number_of_edges() for g in nx_graphs_split_to_four_hours]
num_of_edges_per_day = [g.number_of_edges() for g in nx_graphs_split_to_days]
num_of_edges_per_week = [g.number_of_edges() for g in nx_graphs_split_to_weeks]
num_of_edges_per_month = [g.number_of_edges() for g in nx_graphs_split_to_months]
num_of_edges_per_year = [g.number_of_edges() for g in nx_graphs_split_to_years]

In [33]:
list(zip(num_of_nodes_per_hour, num_of_edges_per_hour))

[(38, 36),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (28, 26),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (27, 26),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (25, 27),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (38, 37),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),


In [34]:
list(zip(num_of_nodes_per_four_hours, num_of_edges_per_four_hours))

[(38, 36),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (28, 26),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (27, 26),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (25, 27),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (38, 37),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (33, 32),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (54, 54),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (29, 30),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (70, 77),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (71, 84),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (37, 45),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (52, 57),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (56, 74),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (50, 61),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (39, 40),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (68, 84),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (60, 74),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (77, 94),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 

In [35]:
list(zip(num_of_nodes_per_day, num_of_edges_per_day))

[(38, 36),
 (28, 26),
 (27, 26),
 (25, 27),
 (38, 37),
 (33, 32),
 (54, 54),
 (29, 30),
 (70, 77),
 (71, 84),
 (37, 45),
 (52, 57),
 (56, 74),
 (50, 61),
 (39, 40),
 (68, 84),
 (60, 74),
 (77, 94),
 (108, 140),
 (98, 111),
 (82, 99),
 (92, 110),
 (81, 108),
 (104, 136),
 (79, 110),
 (85, 145),
 (111, 157),
 (101, 128),
 (109, 125),
 (103, 145),
 (111, 165),
 (136, 175),
 (173, 237),
 (178, 263),
 (129, 155),
 (113, 137),
 (103, 121),
 (204, 291),
 (207, 316),
 (256, 395),
 (291, 495),
 (289, 404),
 (281, 395),
 (262, 410),
 (289, 443),
 (310, 486),
 (318, 534),
 (350, 560),
 (315, 426),
 (313, 465),
 (319, 569),
 (317, 486),
 (335, 566),
 (470, 824),
 (522, 845),
 (489, 595),
 (421, 572),
 (413, 771),
 (462, 769),
 (447, 751),
 (406, 713),
 (449, 748),
 (439, 631),
 (385, 521),
 (473, 794),
 (429, 719),
 (472, 777),
 (525, 892),
 (541, 848),
 (494, 686),
 (444, 549),
 (461, 661),
 (462, 850),
 (495, 868),
 (561, 962),
 (682, 1106),
 (558, 885),
 (548, 783),
 (530, 993),
 (522, 980),
 (

In [36]:
list(zip(num_of_nodes_per_week, num_of_edges_per_week))

[(117, 131),
 (153, 180),
 (198, 267),
 (273, 402),
 (428, 593),
 (686, 1090),
 (873, 1465),
 (1249, 2145),
 (1313, 2243),
 (1452, 2459),
 (1604, 2804),
 (1725, 2993),
 (2112, 3373),
 (2451, 3835),
 (1996, 3237),
 (2256, 3717),
 (1863, 3017),
 (1923, 3381),
 (1487, 2878),
 (1377, 2512),
 (1207, 1753),
 (973, 1288),
 (1246, 1966),
 (1277, 2090),
 (1198, 1874),
 (1208, 1842),
 (1014, 1565),
 (1084, 1648),
 (945, 1392),
 (1040, 1534),
 (876, 1403),
 (824, 1252),
 (860, 1263),
 (733, 1037),
 (815, 1304),
 (759, 1167),
 (836, 1180),
 (552, 761),
 (550, 790),
 (421, 588),
 (276, 345),
 (275, 316),
 (223, 265),
 (199, 230),
 (194, 227),
 (139, 154),
 (117, 126),
 (31, 28),
 (34, 32),
 (19, 17)]

In [37]:
list(zip(num_of_nodes_per_month, num_of_edges_per_month))

[(515, 726),
 (2440, 4152),
 (4277, 7299),
 (5706, 8987),
 (3838, 6669),
 (3203, 5041),
 (2891, 4268),
 (2024, 3234),
 (1810, 2916),
 (836, 1179),
 (375, 438),
 (45, 43)]

In [38]:
list(zip(num_of_nodes_per_year, num_of_edges_per_year))

[(15949, 25764)]

In [46]:
interesting_graphs_candidate_one = nx_graphs_split_to_days[80:120]

In [47]:
for g in interesting_graphs_candidate_one:
    print(g.number_of_nodes())

568
621
627
561
571
669
614
663
750
719
694
676
758
801
909
648
665
633
601
604
666
651
619
625
569
538
624
717
712
726
737
596
611
689
776
648
491
431
475
456


In [222]:
for g in interesting_graphs_candidate_two:
    print(g.number_of_nodes())

18476
43111
50218


In [48]:
import pickle

In [49]:
pickle.dump(interesting_graphs_candidate_one, open(r"C:\Users\nothi\Google Drive\Studies\Courses\Thesis\success_prediction\Pickles\reality_mining\reality_mining_daily.pkl", 'wb'))

In [195]:
pickle.dump(interesting_weekly_graphs_candidate_one, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_one.pkl", 'wb'))
pickle.dump(interesting_weekly_graphs_candidate_two, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_two.pkl", 'wb'))

In [196]:
g1 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_one.pkl", 'rb'))
g2 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_two.pkl", 'rb'))

Would like to compute some labels per node:
1. rank
2. page rank
3. centrality
4. core-number

In [213]:
weekly_graphs_one_with_lables = [{'graph': g} for g in interesting_weekly_graphs_candidate_one]
weekly_graphs_two_with_lables = [{'graph': g} for g in interesting_weekly_graphs_candidate_two]

In [214]:
for g in weekly_graphs_one_with_lables:
    g['core_numbers'] = nx.core_number(g['graph'])
    g['degree_centrality'] = nx.degree_centrality(g['graph'])
    g['betweenness_centrality'] = nx.betweenness_centrality(g['graph'])
    g['pagerank'] = nx.pagerank(g['graph'])
    g['degree'] = nx.degree(g['graph'])
    
for g in weekly_graphs_two_with_lables:
    g['core_numbers'] = nx.core_number(g['graph'])
    g['degree_centrality'] = nx.degree_centrality(g['graph'])
    g['betweenness_centrality'] = nx.betweenness_centrality(g['graph'])
    g['pagerank'] = nx.pagerank(g['graph'])
    g['degree'] = nx.degree(g['graph'])

In [215]:
pickle.dump(weekly_graphs_one_with_lables, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_one.pkl", 'wb'))
pickle.dump(weekly_graphs_two_with_lables, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_two.pkl", 'wb'))

In [216]:
f1 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_one.pkl", 'rb'))
f2 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_two.pkl", 'rb'))

In [217]:
f1

[{'graph': <networkx.classes.digraph.DiGraph at 0x1968ef88908>,
  'core_numbers': {498: 1,
   246: 1,
   673: 1,
   110: 1,
   979: 1,
   1: 1,
   1669: 1,
   1431: 1,
   1323: 1,
   1732: 1,
   352: 1,
   1586: 1,
   1839: 1,
   1969: 1,
   242: 1,
   644: 1,
   1260: 1,
   530: 1,
   1448: 1},
  'degree_centrality': {498: 0.05555555555555555,
   246: 0.2222222222222222,
   673: 0.05555555555555555,
   110: 0.05555555555555555,
   979: 0.05555555555555555,
   1: 0.5555555555555556,
   1669: 0.2222222222222222,
   1431: 0.05555555555555555,
   1323: 0.05555555555555555,
   1732: 0.05555555555555555,
   352: 0.05555555555555555,
   1586: 0.05555555555555555,
   1839: 0.05555555555555555,
   1969: 0.05555555555555555,
   242: 0.05555555555555555,
   644: 0.05555555555555555,
   1260: 0.05555555555555555,
   530: 0.05555555555555555,
   1448: 0.05555555555555555},
  'betweenness_centrality': {498: 0.0,
   246: 0.0,
   673: 0.0,
   110: 0.0,
   979: 0.0,
   1: 0.0,
   1669: 0.0130718954248

In [246]:
first_time = 5
last_time = len(weekly_graphs_one_with_lables)
prev_graph = weekly_graphs_one_with_lables[first_time]['graph']
all_intersection = np.array(prev_graph.nodes())
for g in weekly_graphs_one_with_lables[first_time+1:last_time]:
    all_intersection = np.intersect1d(all_intersection, g['graph'].nodes())
    prev_graph = g['graph']
print(all_intersection, all_intersection.shape)

[   1   56   80  217  223  246  341  350  412  449  453  465  498  511
  539  628  691  713  793  817  841  852  999 1037 1120 1144 1151 1157
 1159 1179 1246 1258 1277 1377 1440 1444 1500 1522 1586 1669 1701 1768
 1792 1797 1839 1874 1889 1894 1930 1987 1998 2027] (52,)


In [247]:
prev_graph = weekly_graphs_two_with_lables[0]['graph']
all_intersection = np.array(prev_graph.nodes())
for g in weekly_graphs_two_with_lables[1:]:
    all_intersection = np.intersect1d(all_intersection, g['graph'].nodes())
    prev_graph = g['graph']
print(all_intersection, all_intersection.shape)

[   1    5   12   14   15   21   24   25   31   32   34   45   47   56
   80   87   90   99  104  120  129  137  151  153  155  165  177  195
  203  205  210  217  220  223  228  245  246  252  263  266  272  278
  279  293  306  312  329  341  345  346  350  358  362  363  385  403
  410  411  412  419  429  434  449  453  457  465  467  479  498  511
  521  536  539  547  549  553  556  558  572  574  585  599  601  605
  620  628  630  634  641  689  690  691  702  705  713  718  723  730
  737  740  764  793  794  795  803  805  817  827  829  833  838  841
  852  853  863  869  882  890  895  897  898  903  904  907  939  943
  956  980  987  991  993  998  999 1019 1037 1052 1058 1070 1073 1080
 1095 1116 1120 1135 1144 1151 1157 1158 1159 1164 1179 1181 1192 1194
 1195 1198 1214 1222 1241 1246 1258 1269 1274 1277 1278 1287 1291 1300
 1302 1306 1309 1323 1328 1369 1374 1377 1380 1384 1385 1393 1430 1434
 1440 1441 1444 1451 1453 1465 1467 1480 1500 1501 1505 1510 1522 1550
 1576 