In [243]:
import numpy as np

In [244]:
datalines = open(r"..\..\..\datasets\Temporal graphs\email-dnc\email-dnc.edges", 'r').readlines()
print(datalines[:10])
datalines = [row.replace('\n', '').split(',') for row in datalines]
print(datalines[:10])
datalines = datalines[:]

['419,465,1463507482\n', '869,453,1462337903\n', '943,1151,1463167636\n', '943,217,1463167636\n', '943,841,1463167636\n', '943,1998,1463167636\n', '882,449,1462324386\n', '882,1159,1462324386\n', '882,1377,1462324386\n', '498,1159,1463756736\n']
[['419', '465', '1463507482'], ['869', '453', '1462337903'], ['943', '1151', '1463167636'], ['943', '217', '1463167636'], ['943', '841', '1463167636'], ['943', '1998', '1463167636'], ['882', '449', '1462324386'], ['882', '1159', '1462324386'], ['882', '1377', '1462324386'], ['498', '1159', '1463756736']]


In [245]:
datalines[:10]

[['419', '465', '1463507482'],
 ['869', '453', '1462337903'],
 ['943', '1151', '1463167636'],
 ['943', '217', '1463167636'],
 ['943', '841', '1463167636'],
 ['943', '1998', '1463167636'],
 ['882', '449', '1462324386'],
 ['882', '1159', '1462324386'],
 ['882', '1377', '1462324386'],
 ['498', '1159', '1463756736']]

In [246]:
froms, tos, times = zip(*[d for d in datalines if not d[2] == '0'])

In [247]:
int_froms = list(map(int, froms))
int_tos = list(map(int, tos))
int_times = list(map(int, times))

In [248]:
DAY_IN_SECONDS = 60*60*24
WEEK_IN_SECONDS = DAY_IN_SECONDS*7
MONTH_IN_SECONDS = DAY_IN_SECONDS*30
YEAR_IN_SECONDS = DAY_IN_SECONDS*365

In [249]:
min_time = np.min(int_times)
max_time = np.max(int_times)
time_span_seconds = max_time-min_time
num_of_days = int(np.ceil(time_span_seconds/DAY_IN_SECONDS))
num_of_weeks = int(np.ceil(time_span_seconds/WEEK_IN_SECONDS))
num_of_months = int(np.ceil(time_span_seconds/MONTH_IN_SECONDS))
num_of_years = int(np.ceil(time_span_seconds/YEAR_IN_SECONDS))


In [250]:
print(f"num of days: {num_of_days}, num of weeks: {num_of_weeks}, num of months: {num_of_months}, num of years: {num_of_years}".format())

num of days: 983, num of weeks: 141, num of months: 33, num of years: 3


In [251]:
np.histogram(int_times, bins=num_of_days)

(array([   1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0, 

In [252]:
np.histogram(int_times, bins=num_of_weeks)

(array([   1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    3,    1,    3,    0,    4,    1,    0,    1,
           6,    8,    9,    2,    2,    2,    2,    1,    6,    4,    1,
           3,    3,    4,    6,    2,    5,    4,    5,   10,    1,   14,
          14,   10,    6,    7,    5,   20,   17,  135,   15,   20,   84,
          48,   34,   53,   31,   18,   25,   66,   45,    5,    3,   16,
          62,   61,   38,   39,   96,   45,  107,   94,   28,   22,   28,
          37,   44,   29,   25, 4952, 9242, 8196, 8578, 6750], dtype=int64),
 array([1.37929863e+09, 1.37990055e

In [223]:
np.histogram(int_times, bins=num_of_months)

(array([    1,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     7,     6,
           25,    10,    13,    18,    20,    48,    97,   257,   130,
          141,   171,   311,   174,  2096, 35739], dtype=int64),
 array([1.37929863e+09, 1.38187044e+09, 1.38444225e+09, 1.38701407e+09,
        1.38958588e+09, 1.39215769e+09, 1.39472950e+09, 1.39730131e+09,
        1.39987312e+09, 1.40244493e+09, 1.40501674e+09, 1.40758855e+09,
        1.41016036e+09, 1.41273217e+09, 1.41530398e+09, 1.41787579e+09,
        1.42044761e+09, 1.42301942e+09, 1.42559123e+09, 1.42816304e+09,
        1.43073485e+09, 1.43330666e+09, 1.43587847e+09, 1.43845028e+09,
        1.44102209e+09, 1.44359390e+09, 1.44616571e+09, 1.44873752e+09,
        1.45130933e+09, 1.45388114e+09, 1.45645296e+09, 1.45902477e+09,
        1.46159658e+09, 1.46416839e+09]))

In [224]:
np.histogram(int_times, bins=num_of_years)

(array([    1,    79, 39184], dtype=int64),
 array([1.37929863e+09, 1.40758855e+09, 1.43587847e+09, 1.46416839e+09]))

In [225]:
def split_by_time_scale(min_time, max_time, time_range, time_scale):
    times = []
    for i in range(time_range):
        time_start = min_time + i*(time_scale)
        time_end = np.min([max_time, min_time + (i+1)*(time_scale)])
        times.append((time_start, time_end))
    return times

In [226]:
days = split_by_time_scale(min_time, max_time, num_of_days, DAY_IN_SECONDS)

In [227]:
weeks = split_by_time_scale(min_time, max_time, num_of_weeks, WEEK_IN_SECONDS)

In [228]:
months = split_by_time_scale(min_time, max_time, num_of_months, MONTH_IN_SECONDS)

In [229]:
years = split_by_time_scale(min_time, max_time, num_of_years, YEAR_IN_SECONDS)

In [230]:
print(f"num of days: {len(days)}, num of weeks: {len(weeks)}, num of months: {len(months)}, num of years: {len(years)}".format())

num of days: 983, num of weeks: 141, num of months: 33, num of years: 3


In [231]:
def split_graphs_by_scale(min_time, time_range, time_scale):
    graphs_split = [[] for i in range(time_range)]
    for n1, n2, t in zip(int_froms, int_tos, int_times):
    #     print(type(n1), type(n2), type(t))
        time_egde_belongs_to = int(np.floor((t - min_time) / time_scale))
        if (n1 == n2):
            continue
        graphs_split[time_egde_belongs_to].append((n1, n2))
    return graphs_split

In [232]:
graphs_split_to_days = split_graphs_by_scale(min_time, num_of_days, DAY_IN_SECONDS)

In [233]:
graphs_split_to_weeks = split_graphs_by_scale(min_time, num_of_weeks, WEEK_IN_SECONDS)

In [234]:
graphs_split_to_months = split_graphs_by_scale(min_time, num_of_months, MONTH_IN_SECONDS)

In [235]:
graphs_split_to_years = split_graphs_by_scale(min_time, num_of_years, YEAR_IN_SECONDS)

In [236]:
print('day graphs num of edges:')
for g in graphs_split_to_days:
    print(len(g))

print('week graphs num of edges:')
for g in graphs_split_to_weeks:
    print(len(g))

print('month graphs num of edges:')
for g in graphs_split_to_months:
    print(len(g))
    
print('year graphs num of edges:')
for g in graphs_split_to_years:
    print(len(g))

day graphs num of edges:
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0

In [237]:
import networkx as nx

In [255]:
nx_graphs_split_to_days = list(map(nx.DiGraph, graphs_split_to_days))
nx_graphs_split_to_weeks = list(map(nx.DiGraph, graphs_split_to_weeks))
nx_graphs_split_to_months = list(map(nx.DiGraph, graphs_split_to_months))
nx_graphs_split_to_years = list(map(nx.DiGraph, graphs_split_to_years))

In [256]:
num_of_nodes_per_day = [g.number_of_nodes() for g in nx_graphs_split_to_days]
num_of_nodes_per_week = [g.number_of_nodes() for g in nx_graphs_split_to_weeks]
num_of_nodes_per_month = [g.number_of_nodes() for g in nx_graphs_split_to_months]
num_of_nodes_per_year = [g.number_of_nodes() for g in nx_graphs_split_to_years]

num_of_edges_per_day = [g.number_of_edges() for g in nx_graphs_split_to_days]
num_of_edges_per_week = [g.number_of_edges() for g in nx_graphs_split_to_weeks]
num_of_edges_per_month = [g.number_of_edges() for g in nx_graphs_split_to_months]
num_of_edges_per_year = [g.number_of_edges() for g in nx_graphs_split_to_years]

In [257]:
list(zip(num_of_nodes_per_day, num_of_edges_per_day))

[(2, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 

In [259]:
for i, e in enumerate(num_of_nodes_per_week):
    if e == 647:
        print(i, e)

print(num_of_nodes_per_week[138], num_of_edges_per_week[138])

138 647
647 1572


In [205]:
list(zip(num_of_nodes_per_week, num_of_edges_per_week))

[(2, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (3, 3),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (2, 1),
 (2, 1),
 (2, 1),
 (0, 0),
 (4, 2),
 (7, 5),
 (4, 4),
 (0, 0),
 (0, 0),
 (0, 0),
 (5, 4),
 (9, 8),
 (0, 0),
 (4, 2),
 (4, 2),
 (12, 9),
 (7, 15),
 (2, 1),
 (11, 13),
 (4, 6),
 (4, 2),
 (5, 6),
 (2, 1),
 (4, 6),
 (27, 99),
 (21, 35),
 (13, 18),
 (11, 7),
 (32, 97),
 (13, 18),
 (20, 29),
 (15, 23),
 (16, 33),
 (22, 37),
 (20, 39),
 (29, 75),
 (31, 53),
 (21, 27),
 (39, 90),
 (37, 74),
 (28, 96),
 (29, 61),
 (27, 49),
 (34, 107),
 (44, 141),
 (50, 352),
 (17, 18),
 (40, 87),
 (41, 89),
 (39, 72),
 (76, 325),
 (40, 68),
 (51, 160),
 (62, 278),
 (65, 140),
 (51, 169),
 (51, 127),
 (58, 98),
 (16, 11),
 (41, 88),
 (48, 90),
 (49, 115),
 (80, 259),
 (69, 207),
 (121, 656),
 (64, 106),
 (88, 276),
 (81, 251),
 (75, 182),
 (104, 741),
 (57, 110),
 (41, 68),
 (54, 161),
 (57, 255),
 (86, 250)

In [206]:
list(zip(num_of_nodes_per_month, num_of_edges_per_month))

[(2, 1),
 (0, 0),
 (0, 0),
 (3, 3),
 (0, 0),
 (6, 3),
 (15, 11),
 (11, 11),
 (18, 16),
 (22, 30),
 (30, 104),
 (71, 160),
 (65, 126),
 (79, 155),
 (111, 299),
 (122, 615),
 (154, 539),
 (173, 615),
 (166, 447),
 (190, 605),
 (282, 1202),
 (238, 1095),
 (259, 898),
 (321, 1987),
 (347, 1639),
 (344, 2076),
 (541, 2821),
 (518, 3181),
 (474, 2558),
 (460, 2312),
 (558, 3734),
 (597, 4344),
 (685, 4557),
 (644, 3634),
 (667, 4090),
 (774, 5851),
 (1134, 11585),
 (945, 9478),
 (917, 8665),
 (1032, 8470),
 (1232, 8926),
 (1050, 12179),
 (936, 7582),
 (1238, 15138),
 (1319, 15104),
 (1372, 16778),
 (954, 22933),
 (1565, 24133),
 (1544, 31968),
 (1370, 15163),
 (1364, 18928),
 (1596, 23201),
 (1449, 13623),
 (1682, 17157),
 (1660, 16677),
 (1955, 27008),
 (1840, 33634),
 (2086, 30571),
 (1645, 21284),
 (1832, 25561),
 (1993, 32484),
 (1843, 24900),
 (1877, 40477),
 (2147, 29952),
 (2346, 28790),
 (2554, 42856),
 (2094, 44324),
 (2260, 26010),
 (2397, 35754),
 (2729, 69896),
 (2276, 50147),
 (

In [207]:
list(zip(num_of_nodes_per_year, num_of_edges_per_year))

[(125, 320),
 (873, 5808),
 (2434, 33092),
 (4481, 125972),
 (6510, 202506),
 (8456, 353190),
 (10241, 393122),
 (11275, 452299),
 (0, 0),
 (23651, 2274544)]

In [297]:
interesting_graphs_candidate_one = nx_graphs_split_to_weeks[:-1]

In [298]:
for g in interesting_graphs_candidate_one:
    print(g.number_of_nodes())

16897
20836


In [222]:
for g in interesting_graphs_candidate_two:
    print(g.number_of_nodes())

18476
43111
50218


In [299]:
import pickle

In [300]:
pickle.dump(interesting_graphs_candidate_one, open(r"..\..\..\success_prediction\Pickles\ia-digg-reply\ia-digg-reply.pkl", 'wb'))