In [1]:
import numpy as np

In [2]:
datalines = open(r"C:\Users\nothi\Google Drive\Studies\Courses\Thesis\datasets\Temporal graphs\fb-wosn-friends\fb-wosn-friends.edges", 'r').readlines()
print(datalines[:10])
datalines = [row.replace('\n', '').split(' ') for row in datalines]
print(datalines[:10])
datalines = datalines[2:]

['% sym unweighted\n', '% 1269502 63731 63731\n', '1 2 1 0\n', '1 2 1 1202446730\n', '1 3 1 0\n', '1 4 1 0\n', '1 4 1 1213591678\n', '1 5 1 0\n', '1 6 1 0\n', '1 7 1 0\n']
[['%', 'sym', 'unweighted'], ['%', '1269502', '63731', '63731'], ['1', '2', '1', '0'], ['1', '2', '1', '1202446730'], ['1', '3', '1', '0'], ['1', '4', '1', '0'], ['1', '4', '1', '1213591678'], ['1', '5', '1', '0'], ['1', '6', '1', '0'], ['1', '7', '1', '0']]


In [3]:
datalines[:10]

[['1', '2', '1', '0'],
 ['1', '2', '1', '1202446730'],
 ['1', '3', '1', '0'],
 ['1', '4', '1', '0'],
 ['1', '4', '1', '1213591678'],
 ['1', '5', '1', '0'],
 ['1', '6', '1', '0'],
 ['1', '7', '1', '0'],
 ['1', '8', '1', '0'],
 ['1', '9', '1', '0']]

In [4]:
froms, tos, _, times = zip(*[d for d in datalines if not d[3] == '0'])

In [7]:
int_froms = list(map(int, froms))
int_tos = list(map(int, tos))
int_times = list(map(int, times))

In [8]:
DAY_IN_SECONDS = 60*60*24
WEEK_IN_SECONDS = DAY_IN_SECONDS*7
MONTH_IN_SECONDS = DAY_IN_SECONDS*30
YEAR_IN_SECONDS = DAY_IN_SECONDS*365

In [9]:
min_time = np.min(int_times)
max_time = np.max(int_times)
time_span_seconds = max_time-min_time
num_of_days = int(np.ceil(time_span_seconds/DAY_IN_SECONDS))
num_of_weeks = int(np.ceil(time_span_seconds/WEEK_IN_SECONDS))
num_of_months = int(np.ceil(time_span_seconds/MONTH_IN_SECONDS))
num_of_years = int(np.ceil(time_span_seconds/YEAR_IN_SECONDS))


In [10]:
print(f"num of days: {num_of_days}, num of weeks: {num_of_weeks}, num of months: {num_of_months}, num of years: {num_of_years}".format())

num of days: 870, num of weeks: 125, num of months: 29, num of years: 3


In [11]:
np.histogram(int_times, bins=num_of_days)

(array([ 203,  228,  288,  200,  144,  236,  267,  230,  244,  238,  207,
         113,  261,  270,  286,  251,  213,  153,  141,  203,  213,  281,
         310,  317,  273,  194,  305,  387,  346,  366,  304,  261,  228,
         296,  419,  412,  416,  395,  254,  203,  306,  350,  377,  385,
         351,  212,  231,  321,  381,  362,  330,  332,  250,  170,  259,
         341,  311,  325,  328,  218,  214,  296,  333,  327,  326,  254,
         253,  173,  294,  337,  371,  371,  335,  228,  173,  278,  345,
         308,  283,  207,  175,  215,  351,  422,  376,  375,  331,  234,
         220,  276,  355,  335,  389,  352,  271,  236,  318,  344,  361,
         318,  321,  240,  220,  296,  322,  258,  364,  345,  249,  234,
         248,  179,  233,  334,  289,  338,  314,  222,  268,  366,  353,
         368,  321,  269,  395,  379,  333,  338,  321,  302,  255,  282,
         390,  397,  368,  348,  270,  276,  327,  378,  385,  402,  356,
         296,  284,  389,  356,  378, 

In [12]:
np.histogram(int_times, bins=num_of_weeks)

(array([ 1564,  1564,  1460,  2060,  2213,  2325,  2230,  2005,  2007,
         1928,  2097,  1858,  2201,  2223,  2066,  1980,  1895,  2372,
         2178,  2372,  2488,  2538,  2421,  2038,  2591,  2635,  2655,
         2555,  2665,  2299,  2214,  2879,  2756,  2514,  2616,  2787,
         2788,  3004,  2837,  3436,  3459,  3439,  3410,  3183,  3530,
         4298,  3795,  4459,  4618,  3959,  3846,  3870,  3783,  4242,
         4549,  4773,  4533,  4468,  4141,  4027,  3747,  4201,  4542,
         3677,  4405,  3796,  3791,  3381,  2415,  2890,  3149,  3600,
         3621,  3701,  3087,  3926,  3688,  4159,  4410,  4413,  3660,
         5795, 12412, 10056,  7963,  8608,  9094,  8838,  8622,  9208,
         8829,  9208,  9639,  8690,  9833, 10290, 10015, 10833, 11602,
        12083, 12348, 12437, 13730, 14757,  8999, 12371, 14862, 14487,
        14113, 14688, 15007, 16137, 16019, 15679, 17557, 18763, 18103,
        17886, 20987, 20764, 20379, 19429,  5027,    15,    18],
       dtype

In [13]:
np.histogram(int_times, bins=num_of_months)

(array([ 7368,  9328,  8681,  8919, 10325, 10294, 10987, 11419, 12115,
        14549, 16274, 18072, 18328, 18405, 17899, 14619, 14129, 15877,
        19126, 41582, 38377, 40129, 46300, 54693, 56356, 64996, 72892,
        85492, 30604], dtype=int64),
 array([1.15745493e+09, 1.16004532e+09, 1.16263570e+09, 1.16522609e+09,
        1.16781647e+09, 1.17040686e+09, 1.17299725e+09, 1.17558763e+09,
        1.17817802e+09, 1.18076840e+09, 1.18335879e+09, 1.18594918e+09,
        1.18853956e+09, 1.19112995e+09, 1.19372033e+09, 1.19631072e+09,
        1.19890111e+09, 1.20149149e+09, 1.20408188e+09, 1.20667226e+09,
        1.20926265e+09, 1.21185304e+09, 1.21444342e+09, 1.21703381e+09,
        1.21962419e+09, 1.22221458e+09, 1.22480497e+09, 1.22739535e+09,
        1.22998574e+09, 1.23257612e+09]))

In [14]:
np.histogram(int_times, bins=num_of_years)

(array([ 99303, 173956, 514876], dtype=int64),
 array([1.15745493e+09, 1.18249533e+09, 1.20753573e+09, 1.23257612e+09]))

In [15]:
def split_by_time_scale(min_time, max_time, time_range, time_scale):
    times = []
    for i in range(time_range):
        time_start = min_time + i*(time_scale)
        time_end = np.min([max_time, min_time + (i+1)*(time_scale)])
        times.append((time_start, time_end))
    return times

In [16]:
days = split_by_time_scale(min_time, max_time, num_of_days, DAY_IN_SECONDS)

In [17]:
weeks = split_by_time_scale(min_time, max_time, num_of_weeks, WEEK_IN_SECONDS)

In [18]:
months = split_by_time_scale(min_time, max_time, num_of_months, MONTH_IN_SECONDS)

In [19]:
years = split_by_time_scale(min_time, max_time, num_of_years, YEAR_IN_SECONDS)

In [20]:
print(f"num of days: {len(days)}, num of weeks: {len(weeks)}, num of months: {len(months)}, num of years: {len(years)}".format())

num of days: 870, num of weeks: 125, num of months: 29, num of years: 3


In [21]:
def split_graphs_by_scale(min_time, time_range, time_scale):
    graphs_split = [[] for i in range(time_range)]
    for n1, n2, t in zip(int_froms, int_tos, int_times):
    #     print(type(n1), type(n2), type(t))
        time_egde_belongs_to = int(np.floor((t - min_time) / time_scale))
        if (n1 == n2):
            continue
        graphs_split[time_egde_belongs_to].append((n1, n2))
    return graphs_split

In [22]:
graphs_split_to_days = split_graphs_by_scale(min_time, num_of_days, DAY_IN_SECONDS)

In [23]:
graphs_split_to_weeks = split_graphs_by_scale(min_time, num_of_weeks, WEEK_IN_SECONDS)

In [24]:
graphs_split_to_months = split_graphs_by_scale(min_time, num_of_months, MONTH_IN_SECONDS)

In [25]:
graphs_split_to_years = split_graphs_by_scale(min_time, num_of_years, YEAR_IN_SECONDS)

In [26]:
print('day graphs num of edges:')
for g in graphs_split_to_days:
    print(len(g))

print('week graphs num of edges:')
for g in graphs_split_to_weeks:
    print(len(g))

print('month graphs num of edges:')
for g in graphs_split_to_months:
    print(len(g))
    
print('year graphs num of edges:')
for g in graphs_split_to_years:
    print(len(g))

day graphs num of edges:
203
228
288
200
144
236
267
230
244
238
207
113
261
270
286
251
214
152
141
204
213
282
308
317
273
194
305
388
347
366
303
262
226
296
419
412
419
392
254
204
305
350
380
384
352
209
232
322
380
363
330
331
249
170
259
341
314
323
327
218
214
297
333
326
326
257
252
172
294
336
371
371
336
230
170
278
347
307
282
208
175
214
352
421
376
375
332
235
221
273
356
335
388
354
271
239
315
343
360
319
322
241
220
293
322
261
361
347
253
229
250
176
241
329
287
344
311
222
270
361
356
370
317
272
392
379
338
331
327
305
250
281
389
398
368
347
270
280
323
379
386
403
352
302
290
378
358
377
419
393
286
320
390
449
381
387
377
252
245
331
397
422
314
314
221
164
210
248
269
452
470
403
306
442
432
402
402
402
316
291
394
485
475
447
389
317
247
305
417
407
447
398
320
219
360
478
443
399
377
315
265
407
422
345
358
335
288
261
306
357
331
360
344
256
265
321
478
527
410
404
357
368
418
506
492
433
404
273
275
355
405
419
475
370
266
237
381
470
386
435
325
351
271
391

In [27]:
import networkx as nx

In [28]:
nx_graphs_split_to_days = list(map(nx.Graph, graphs_split_to_days))
nx_graphs_split_to_weeks = list(map(nx.Graph, graphs_split_to_weeks))
nx_graphs_split_to_months = list(map(nx.Graph, graphs_split_to_months))
nx_graphs_split_to_years = list(map(nx.Graph, graphs_split_to_years))

In [29]:
num_of_nodes_per_day = [g.number_of_nodes() for g in nx_graphs_split_to_days]
num_of_nodes_per_week = [g.number_of_nodes() for g in nx_graphs_split_to_weeks]
num_of_nodes_per_month = [g.number_of_nodes() for g in nx_graphs_split_to_months]
num_of_nodes_per_year = [g.number_of_nodes() for g in nx_graphs_split_to_years]

num_of_edges_per_day = [g.number_of_edges() for g in nx_graphs_split_to_days]
num_of_edges_per_week = [g.number_of_edges() for g in nx_graphs_split_to_weeks]
num_of_edges_per_month = [g.number_of_edges() for g in nx_graphs_split_to_months]
num_of_edges_per_year = [g.number_of_edges() for g in nx_graphs_split_to_years]

In [30]:
list(zip(num_of_nodes_per_day, num_of_edges_per_day))

[(299, 177),
 (341, 207),
 (411, 258),
 (295, 172),
 (208, 124),
 (332, 202),
 (394, 237),
 (341, 203),
 (350, 212),
 (326, 202),
 (284, 178),
 (177, 98),
 (346, 223),
 (380, 233),
 (391, 246),
 (354, 218),
 (306, 179),
 (230, 136),
 (209, 122),
 (310, 182),
 (327, 190),
 (390, 241),
 (423, 265),
 (446, 279),
 (398, 238),
 (301, 178),
 (396, 248),
 (528, 327),
 (498, 302),
 (497, 313),
 (423, 261),
 (381, 230),
 (307, 185),
 (409, 255),
 (590, 361),
 (538, 347),
 (563, 362),
 (545, 353),
 (390, 222),
 (310, 180),
 (431, 258),
 (511, 300),
 (522, 328),
 (516, 323),
 (510, 303),
 (307, 178),
 (322, 200),
 (430, 267),
 (522, 321),
 (472, 302),
 (463, 282),
 (476, 288),
 (361, 212),
 (245, 147),
 (378, 225),
 (465, 288),
 (464, 283),
 (450, 273),
 (470, 285),
 (349, 199),
 (315, 182),
 (423, 254),
 (479, 291),
 (448, 281),
 (450, 274),
 (389, 232),
 (376, 232),
 (255, 151),
 (397, 259),
 (469, 294),
 (501, 317),
 (494, 318),
 (476, 292),
 (337, 200),
 (269, 154),
 (380, 246),
 (500, 303),


In [31]:
list(zip(num_of_nodes_per_week, num_of_edges_per_week))

[(1559, 1315),
 (1520, 1286),
 (1431, 1194),
 (1966, 1688),
 (2042, 1817),
 (2204, 1908),
 (2130, 1840),
 (1981, 1666),
 (2059, 1678),
 (1973, 1639),
 (2025, 1733),
 (1941, 1609),
 (2158, 1779),
 (2265, 1838),
 (2094, 1704),
 (1887, 1534),
 (1966, 1639),
 (2365, 1995),
 (2210, 1841),
 (2333, 1926),
 (2361, 2007),
 (2534, 2149),
 (2422, 1964),
 (1971, 1546),
 (2564, 2248),
 (2614, 2206),
 (2563, 2096),
 (2565, 2159),
 (2572, 2166),
 (2388, 1843),
 (2406, 1916),
 (2841, 2430),
 (2736, 2161),
 (2711, 2142),
 (2698, 2141),
 (2798, 2315),
 (2803, 2267),
 (2919, 2428),
 (2964, 2487),
 (3189, 2802),
 (3292, 2858),
 (3277, 2866),
 (3123, 2563),
 (3119, 2696),
 (3436, 2971),
 (3862, 3348),
 (3648, 3190),
 (4066, 3645),
 (4089, 3565),
 (3611, 3066),
 (3797, 3168),
 (3587, 2928),
 (3949, 3240),
 (4083, 3517),
 (4289, 3704),
 (4468, 3889),
 (4323, 3645),
 (4235, 3529),
 (4016, 3351),
 (3970, 3160),
 (3958, 3200),
 (4335, 3575),
 (4357, 3590),
 (3846, 3062),
 (4198, 3385),
 (3982, 3100),
 (3819, 29

In [32]:
list(zip(num_of_nodes_per_month, num_of_edges_per_month))

[(4193, 6023),
 (5135, 7565),
 (5143, 7104),
 (5337, 7245),
 (5988, 8380),
 (6195, 8341),
 (6439, 8916),
 (6972, 9222),
 (7280, 9795),
 (8045, 11640),
 (8791, 12968),
 (9714, 14260),
 (10305, 14657),
 (10897, 14719),
 (11189, 14411),
 (10341, 11871),
 (10486, 11576),
 (11467, 12820),
 (12705, 15464),
 (17221, 32547),
 (17097, 30258),
 (18392, 31510),
 (20590, 36154),
 (23249, 42680),
 (24044, 43371),
 (26637, 50042),
 (29267, 55760),
 (33201, 65868),
 (19430, 22186)]

In [33]:
list(zip(num_of_nodes_per_year, num_of_edges_per_year))

[(18476, 113236), (43111, 278696), (50218, 223449)]

In [34]:
interesting_graphs_candidate_one = nx_graphs_split_to_weeks[:-1]

In [35]:
for g in interesting_graphs_candidate_one:
    print(g.number_of_nodes())

1559
1520
1431
1966
2042
2204
2130
1981
2059
1973
2025
1941
2158
2265
2094
1887
1966
2365
2210
2333
2361
2534
2422
1971
2564
2614
2563
2565
2572
2388
2406
2841
2736
2711
2698
2798
2803
2919
2964
3189
3292
3277
3123
3119
3436
3862
3648
4066
4089
3611
3797
3587
3949
4083
4289
4468
4323
4235
4016
3970
3958
4335
4357
3846
4198
3982
3819
3266
2823
3363
3625
3782
4049
3433
3992
4077
4092
4432
4572
4277
3966
7938
8574
7328
7279
7628
7457
7435
7433
7191
7574
8010
7706
7879
8531
8221
8996
9000
9754
9791
9936
10472
11174
9632
8489
11183
11407
11190
11351
11715
12260
12567
12119
12979
13958
13978
13402
15283
15445
15609
14711
9168
26
28


fb-wosn-friends-1 times

In [41]:
months[-10:-1]

[(1206702929, 1209294929),
 (1209294929, 1211886929),
 (1211886929, 1214478929),
 (1214478929, 1217070929),
 (1217070929, 1219662929),
 (1219662929, 1222254929),
 (1222254929, 1224846929),
 (1224846929, 1227438929),
 (1227438929, 1230030929)]

fb-wosn-friends-2 times

In [42]:
years

[(1157454929, 1188990929), (1188990929, 1220526929), (1220526929, 1232576125)]

In [36]:
for g in interesting_graphs_candidate_two:
    print(g.number_of_nodes())

NameError: name 'interesting_graphs_candidate_two' is not defined

In [299]:
import pickle

In [300]:
pickle.dump(interesting_graphs_candidate_one, open(r"C:\Users\nothi\Google Drive\Studies\Courses\Thesis\success_prediction\Pickles\ia-digg-reply\ia-digg-reply.pkl", 'wb'))

In [195]:
pickle.dump(interesting_weekly_graphs_candidate_one, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_one.pkl", 'wb'))
pickle.dump(interesting_weekly_graphs_candidate_two, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_two.pkl", 'wb'))

In [196]:
g1 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_one.pkl", 'rb'))
g2 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_candidate_two.pkl", 'rb'))

Would like to compute some labels per node:
1. rank
2. page rank
3. centrality
4. core-number

In [213]:
weekly_graphs_one_with_lables = [{'graph': g} for g in interesting_weekly_graphs_candidate_one]
weekly_graphs_two_with_lables = [{'graph': g} for g in interesting_weekly_graphs_candidate_two]

In [214]:
for g in weekly_graphs_one_with_lables:
    g['core_numbers'] = nx.core_number(g['graph'])
    g['degree_centrality'] = nx.degree_centrality(g['graph'])
    g['betweenness_centrality'] = nx.betweenness_centrality(g['graph'])
    g['pagerank'] = nx.pagerank(g['graph'])
    g['degree'] = nx.degree(g['graph'])
    
for g in weekly_graphs_two_with_lables:
    g['core_numbers'] = nx.core_number(g['graph'])
    g['degree_centrality'] = nx.degree_centrality(g['graph'])
    g['betweenness_centrality'] = nx.betweenness_centrality(g['graph'])
    g['pagerank'] = nx.pagerank(g['graph'])
    g['degree'] = nx.degree(g['graph'])

In [215]:
pickle.dump(weekly_graphs_one_with_lables, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_one.pkl", 'wb'))
pickle.dump(weekly_graphs_two_with_lables, open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_two.pkl", 'wb'))

In [216]:
f1 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_one.pkl", 'rb'))
f2 = pickle.load(open(r"C:\Users\nothi\Documents\Studies\Thesis\Jupyter notebooks\pickles\dnc_with_labels_candidate_two.pkl", 'rb'))

In [217]:
f1

[{'graph': <networkx.classes.digraph.DiGraph at 0x1968ef88908>,
  'core_numbers': {498: 1,
   246: 1,
   673: 1,
   110: 1,
   979: 1,
   1: 1,
   1669: 1,
   1431: 1,
   1323: 1,
   1732: 1,
   352: 1,
   1586: 1,
   1839: 1,
   1969: 1,
   242: 1,
   644: 1,
   1260: 1,
   530: 1,
   1448: 1},
  'degree_centrality': {498: 0.05555555555555555,
   246: 0.2222222222222222,
   673: 0.05555555555555555,
   110: 0.05555555555555555,
   979: 0.05555555555555555,
   1: 0.5555555555555556,
   1669: 0.2222222222222222,
   1431: 0.05555555555555555,
   1323: 0.05555555555555555,
   1732: 0.05555555555555555,
   352: 0.05555555555555555,
   1586: 0.05555555555555555,
   1839: 0.05555555555555555,
   1969: 0.05555555555555555,
   242: 0.05555555555555555,
   644: 0.05555555555555555,
   1260: 0.05555555555555555,
   530: 0.05555555555555555,
   1448: 0.05555555555555555},
  'betweenness_centrality': {498: 0.0,
   246: 0.0,
   673: 0.0,
   110: 0.0,
   979: 0.0,
   1: 0.0,
   1669: 0.0130718954248

In [246]:
first_time = 5
last_time = len(weekly_graphs_one_with_lables)
prev_graph = weekly_graphs_one_with_lables[first_time]['graph']
all_intersection = np.array(prev_graph.nodes())
for g in weekly_graphs_one_with_lables[first_time+1:last_time]:
    all_intersection = np.intersect1d(all_intersection, g['graph'].nodes())
    prev_graph = g['graph']
print(all_intersection, all_intersection.shape)

[   1   56   80  217  223  246  341  350  412  449  453  465  498  511
  539  628  691  713  793  817  841  852  999 1037 1120 1144 1151 1157
 1159 1179 1246 1258 1277 1377 1440 1444 1500 1522 1586 1669 1701 1768
 1792 1797 1839 1874 1889 1894 1930 1987 1998 2027] (52,)


In [247]:
prev_graph = weekly_graphs_two_with_lables[0]['graph']
all_intersection = np.array(prev_graph.nodes())
for g in weekly_graphs_two_with_lables[1:]:
    all_intersection = np.intersect1d(all_intersection, g['graph'].nodes())
    prev_graph = g['graph']
print(all_intersection, all_intersection.shape)

[   1    5   12   14   15   21   24   25   31   32   34   45   47   56
   80   87   90   99  104  120  129  137  151  153  155  165  177  195
  203  205  210  217  220  223  228  245  246  252  263  266  272  278
  279  293  306  312  329  341  345  346  350  358  362  363  385  403
  410  411  412  419  429  434  449  453  457  465  467  479  498  511
  521  536  539  547  549  553  556  558  572  574  585  599  601  605
  620  628  630  634  641  689  690  691  702  705  713  718  723  730
  737  740  764  793  794  795  803  805  817  827  829  833  838  841
  852  853  863  869  882  890  895  897  898  903  904  907  939  943
  956  980  987  991  993  998  999 1019 1037 1052 1058 1070 1073 1080
 1095 1116 1120 1135 1144 1151 1157 1158 1159 1164 1179 1181 1192 1194
 1195 1198 1214 1222 1241 1246 1258 1269 1274 1277 1278 1287 1291 1300
 1302 1306 1309 1323 1328 1369 1374 1377 1380 1384 1385 1393 1430 1434
 1440 1441 1444 1451 1453 1465 1467 1480 1500 1501 1505 1510 1522 1550
 1576 