In [1]:
import numpy as np

In [6]:
datalines = open(r"..\..\..\datasets\Temporal graphs\cambridge_haggle\Exp6.tar\Exp6\contacts.Exp6.dat", 'r').readlines()
print(datalines[:10])
datalines = [row.replace('\n', '').split('\t') for row in datalines]
print(datalines[:10])
datalines = datalines[2:]

['1\t3\t51293\t51293\t1\t0\n', '1\t3\t60603\t60603\t2\t9310\n', '1\t3\t62363\t62363\t3\t1760\n', '1\t3\t79649\t79649\t4\t17286\n', '1\t3\t80129\t80734\t5\t480\n', '1\t3\t80969\t80969\t6\t235\n', '1\t3\t81330\t81330\t7\t361\n', '1\t3\t81351\t82787\t8\t21\n', '1\t3\t83152\t83401\t9\t365\n', '1\t3\t83644\t83644\t10\t243\n']
[['1', '3', '51293', '51293', '1', '0'], ['1', '3', '60603', '60603', '2', '9310'], ['1', '3', '62363', '62363', '3', '1760'], ['1', '3', '79649', '79649', '4', '17286'], ['1', '3', '80129', '80734', '5', '480'], ['1', '3', '80969', '80969', '6', '235'], ['1', '3', '81330', '81330', '7', '361'], ['1', '3', '81351', '82787', '8', '21'], ['1', '3', '83152', '83401', '9', '365'], ['1', '3', '83644', '83644', '10', '243']]


In [3]:
datalines[:10]

[['1', '3', '62363', '62363', '3', '1760'],
 ['1', '3', '79649', '79649', '4', '17286'],
 ['1', '3', '80129', '80734', '5', '480'],
 ['1', '3', '80969', '80969', '6', '235'],
 ['1', '3', '81330', '81330', '7', '361'],
 ['1', '3', '81351', '82787', '8', '21'],
 ['1', '3', '83152', '83401', '9', '365'],
 ['1', '3', '83644', '83644', '10', '243'],
 ['1', '3', '83892', '84361', '11', '248'],
 ['1', '3', '84615', '84740', '12', '254']]

In [4]:
froms, tos, times_s, times_e, _, _ = zip(*[d for d in datalines])

In [5]:
int_froms = list(map(int, froms))
int_tos = list(map(int, tos))
int_times_s = list(map(int, times_s))
int_times_e = list(map(int, times_e))

In [6]:
int_times = np.add(int_times_e, int_times_s)/2

In [7]:
HOUR_IN_SECONDS = 60*60
FOUR_HOURS_IN_SECONDS = HOUR_IN_SECONDS * 4
DAY_IN_SECONDS = HOUR_IN_SECONDS*24
WEEK_IN_SECONDS = DAY_IN_SECONDS*7
MONTH_IN_SECONDS = DAY_IN_SECONDS*30
YEAR_IN_SECONDS = DAY_IN_SECONDS*365

In [8]:
min_time = np.min(int_times)
max_time = np.max(int_times)
time_span_seconds = max_time-min_time
num_of_hours = int(np.ceil(time_span_seconds/HOUR_IN_SECONDS))
num_of_four_hours = int(np.ceil(time_span_seconds/FOUR_HOURS_IN_SECONDS))
num_of_days = int(np.ceil(time_span_seconds/DAY_IN_SECONDS))
num_of_weeks = int(np.ceil(time_span_seconds/WEEK_IN_SECONDS))
num_of_months = int(np.ceil(time_span_seconds/MONTH_IN_SECONDS))
num_of_years = int(np.ceil(time_span_seconds/YEAR_IN_SECONDS))


In [9]:
print(f"num of hours: {num_of_hours}, num of four hours: {num_of_four_hours}, num of days: {num_of_days}, num of weeks: {num_of_weeks}, num of months: {num_of_months}, num of years: {num_of_years}".format())

num of hours: 94, num of four hours: 24, num of days: 4, num of weeks: 1, num of months: 1, num of years: 1


In [10]:
np.histogram(int_times, bins=num_of_hours)

(array([ 7928,  8665,  6332,  1201,  1035,   977,   528,   328,   265,
          260,   150,   165,  1944, 11495,  7727,  6387,  7182,  7187,
         6187,  5277,  5695,  5652,  6139,  6163,  1813,  1208,   990,
          874,   904,   562,   709,   567,   559,   705,   677,   540,
          551,  2068,  6785,  8113,  7893,  6892,  5970,  5541,  4964,
         4006,  3501,  3162,  2319,  3961,  1796,   701,   634,   431,
          439,   378,   374,   290,   304,   278,   559,  1915,  2942,
         3367,  3263,  3080,  3080,  2447,  2501,  2526,  1981,  1325,
          609,   383,   424,   650,   345,   214,   165,   130,   122,
          159,   192,   274,   493,   992,  1294,  1315,  1393,  1376,
          924,   565,   284,    38], dtype=int64),
 array([  6561.        ,  10139.23404255,  13717.46808511,  17295.70212766,
         20873.93617021,  24452.17021277,  28030.40425532,  31608.63829787,
         35186.87234043,  38765.10638298,  42343.34042553,  45921.57446809,
         49

In [11]:
np.histogram(int_times, bins=num_of_four_hours)

(array([24062,  2897,   813, 25469, 25892, 22982,  7091,  2936,  2448,
        11069, 28033, 17569, 11137,  2239,  1331,  4845, 12575,  9619,
         3478,  1523,   549,  2162,  5205,  1731], dtype=int64),
 array([  6561.  ,  20575.75,  34590.5 ,  48605.25,  62620.  ,  76634.75,
         90649.5 , 104664.25, 118679.  , 132693.75, 146708.5 , 160723.25,
        174738.  , 188752.75, 202767.5 , 216782.25, 230797.  , 244811.75,
        258826.5 , 272841.25, 286856.  , 300870.75, 314885.5 , 328900.25,
        342915.  ]))

In [12]:
np.histogram(int_times, bins=num_of_days)

(array([102115,  69146,  41746,  14648], dtype=int64),
 array([  6561. ,  90649.5, 174738. , 258826.5, 342915. ]))

In [13]:
np.histogram(int_times, bins=num_of_weeks)

(array([227655], dtype=int64), array([  6561., 342915.]))

In [14]:
def split_by_time_scale(min_time, max_time, time_range, time_scale):
    times = []
    for i in range(time_range):
        time_start = min_time + i*(time_scale)
        time_end = np.min([max_time, min_time + (i+1)*(time_scale)])
        times.append((time_start, time_end))
    return times

In [15]:
hours = split_by_time_scale(min_time, max_time, num_of_hours, HOUR_IN_SECONDS)

In [16]:
four_hours = split_by_time_scale(min_time, max_time, num_of_four_hours, FOUR_HOURS_IN_SECONDS)

In [17]:
days = split_by_time_scale(min_time, max_time, num_of_days, DAY_IN_SECONDS)

In [18]:
weeks = split_by_time_scale(min_time, max_time, num_of_weeks, WEEK_IN_SECONDS)

In [19]:
months = split_by_time_scale(min_time, max_time, num_of_months, MONTH_IN_SECONDS)

In [20]:
years = split_by_time_scale(min_time, max_time, num_of_years, YEAR_IN_SECONDS)

In [21]:
print(f"num of hours: {len(hours)}, num of four hours: {len(four_hours)}, num of days: {len(days)}, num of weeks: {len(weeks)}, num of months: {len(months)}, num of years: {len(years)}".format())

num of hours: 94, num of four hours: 24, num of days: 4, num of weeks: 1, num of months: 1, num of years: 1


In [22]:
def split_graphs_by_scale(min_time, time_range, time_scale):
    graphs_split = [[] for i in range(time_range)]
    for n1, n2, t in zip(int_froms, int_tos, int_times):
    #     print(type(n1), type(n2), type(t))
        time_egde_belongs_to = int(np.floor((t - min_time) / time_scale))
        if (n1 == n2):
            continue
        graphs_split[time_egde_belongs_to].append((n1, n2))
    return graphs_split

In [23]:
graphs_split_to_hours = split_graphs_by_scale(min_time, num_of_hours, HOUR_IN_SECONDS)

In [24]:
graphs_split_to_four_hours = split_graphs_by_scale(min_time, num_of_four_hours, FOUR_HOURS_IN_SECONDS)

In [25]:
graphs_split_to_days = split_graphs_by_scale(min_time, num_of_days, DAY_IN_SECONDS)

In [26]:
graphs_split_to_weeks = split_graphs_by_scale(min_time, num_of_weeks, WEEK_IN_SECONDS)

In [27]:
graphs_split_to_months = split_graphs_by_scale(min_time, num_of_months, MONTH_IN_SECONDS)

In [28]:
graphs_split_to_years = split_graphs_by_scale(min_time, num_of_years, YEAR_IN_SECONDS)

In [29]:
print('hour graphs num of edges:')
for g in graphs_split_to_hours:
    print(len(g))

print('four hour graphs num of edges:')
for g in graphs_split_to_four_hours:
    print(len(g))

print('day graphs num of edges:')
for g in graphs_split_to_days:
    print(len(g))

print('week graphs num of edges:')
for g in graphs_split_to_weeks:
    print(len(g))

print('month graphs num of edges:')
for g in graphs_split_to_months:
    print(len(g))
    
print('year graphs num of edges:')
for g in graphs_split_to_years:
    print(len(g))

hour graphs num of edges:
7951
8832
6201
1170
1049
964
510
331
258
272
139
185
2452
11905
7422
6515
7194
7202
6177
5192
5677
5753
6250
5729
1582
1140
957
907
838
570
716
578
527
776
644
494
690
3211
7209
8508
7426
6870
5721
5398
5020
3599
3651
2764
2792
3537
1301
685
548
413
432
362
359
309
285
320
900
2589
2951
3552
3065
3326
2678
2469
2590
2282
1735
1035
470
388
495
576
239
227
149
106
136
170
252
286
764
1325
1179
1479
1224
1308
745
379
113
4
four hour graphs num of edges:
24154
2854
854
28294
25765
23409
4586
2702
2441
19618
25415
15034
8315
1755
1273
9992
11538
7642
1929
721
844
4747
3656
117
day graphs num of edges:
105330
69796
40515
12014
week graphs num of edges:
227655
month graphs num of edges:
227655
year graphs num of edges:
227655


In [30]:
import networkx as nx

In [31]:
nx_graphs_split_to_hours = list(map(nx.Graph, graphs_split_to_hours))
nx_graphs_split_to_four_hours = list(map(nx.Graph, graphs_split_to_four_hours))
nx_graphs_split_to_days = list(map(nx.Graph, graphs_split_to_days))
nx_graphs_split_to_weeks = list(map(nx.Graph, graphs_split_to_weeks))
nx_graphs_split_to_months = list(map(nx.Graph, graphs_split_to_months))
nx_graphs_split_to_years = list(map(nx.Graph, graphs_split_to_years))

In [32]:
num_of_nodes_per_hour = [g.number_of_nodes() for g in nx_graphs_split_to_hours]
num_of_nodes_per_four_hours = [g.number_of_nodes() for g in nx_graphs_split_to_four_hours]
num_of_nodes_per_day = [g.number_of_nodes() for g in nx_graphs_split_to_days]
num_of_nodes_per_week = [g.number_of_nodes() for g in nx_graphs_split_to_weeks]
num_of_nodes_per_month = [g.number_of_nodes() for g in nx_graphs_split_to_months]
num_of_nodes_per_year = [g.number_of_nodes() for g in nx_graphs_split_to_years]

num_of_edges_per_hour = [g.number_of_edges() for g in nx_graphs_split_to_hours]
num_of_edges_per_four_hours = [g.number_of_edges() for g in nx_graphs_split_to_four_hours]
num_of_edges_per_day = [g.number_of_edges() for g in nx_graphs_split_to_days]
num_of_edges_per_week = [g.number_of_edges() for g in nx_graphs_split_to_weeks]
num_of_edges_per_month = [g.number_of_edges() for g in nx_graphs_split_to_months]
num_of_edges_per_year = [g.number_of_edges() for g in nx_graphs_split_to_years]

In [33]:
list(zip(num_of_nodes_per_hour, num_of_edges_per_hour))

[(139, 1969),
 (169, 1508),
 (365, 1800),
 (234, 527),
 (167, 379),
 (213, 431),
 (146, 270),
 (128, 155),
 (98, 98),
 (89, 89),
 (68, 65),
 (87, 86),
 (127, 956),
 (170, 1576),
 (200, 1812),
 (203, 1402),
 (228, 1938),
 (257, 1308),
 (362, 1864),
 (348, 1725),
 (356, 1411),
 (323, 1597),
 (288, 1410),
 (316, 1504),
 (426, 925),
 (433, 688),
 (276, 475),
 (283, 453),
 (281, 447),
 (201, 300),
 (170, 290),
 (153, 235),
 (152, 204),
 (164, 273),
 (157, 246),
 (152, 231),
 (208, 333),
 (313, 1672),
 (217, 2095),
 (227, 2897),
 (234, 2889),
 (196, 2690),
 (212, 2160),
 (227, 2195),
 (212, 2075),
 (232, 1582),
 (229, 1726),
 (250, 1485),
 (201, 1256),
 (251, 1438),
 (206, 605),
 (235, 355),
 (216, 284),
 (135, 170),
 (157, 183),
 (115, 161),
 (119, 149),
 (96, 106),
 (88, 101),
 (128, 143),
 (229, 506),
 (256, 1252),
 (243, 1298),
 (249, 1732),
 (213, 1227),
 (241, 1685),
 (222, 1379),
 (222, 1139),
 (247, 1286),
 (343, 1180),
 (418, 1116),
 (391, 670),
 (233, 290),
 (141, 185),
 (209, 260)

In [34]:
list(zip(num_of_nodes_per_four_hours, num_of_edges_per_four_hours))

[(522, 2946),
 (351, 864),
 (143, 189),
 (331, 2902),
 (729, 3762),
 (828, 3300),
 (927, 2039),
 (437, 876),
 (237, 480),
 (520, 4206),
 (405, 5469),
 (450, 4270),
 (521, 2434),
 (340, 558),
 (198, 284),
 (498, 3221),
 (370, 3462),
 (786, 3166),
 (519, 795),
 (176, 223),
 (181, 260),
 (436, 1707),
 (273, 1262),
 (45, 74)]

In [35]:
list(zip(num_of_nodes_per_day, num_of_edges_per_day))

[(1899, 8781), (1792, 10427), (1597, 8744), (1029, 3434)]

In [36]:
list(zip(num_of_nodes_per_week, num_of_edges_per_week))

[(4519, 21181)]

In [37]:
list(zip(num_of_nodes_per_month, num_of_edges_per_month))

[(4519, 21181)]

In [38]:
list(zip(num_of_nodes_per_year, num_of_edges_per_year))

[(4519, 21181)]

In [39]:
interesting_graphs_candidate_one = nx_graphs_split_to_hours[38:47]

In [42]:
for g in interesting_graphs_candidate_one:
    print(g.number_of_nodes(), g.number_of_edges())

217 2095
227 2897
234 2889
196 2690
212 2160
227 2195
212 2075
232 1582
229 1726


In [222]:
for g in interesting_graphs_candidate_two:
    print(g.number_of_nodes())

18476
43111
50218


In [95]:
import pickle

In [96]:
pickle.dump(interesting_graphs_candidate_one, open(r"..\..\..\success_prediction\Pickles\cambridge_haggle\infocom06_hours.pkl", 'wb'))